definitions:
  script: &build |-
    - docker login --username $DOCKER_HUB_USER --password $DOCKER_HUB_PASS
    - docker build --build-arg POSTGRES_VERSION=$VERSION -t $IMAGE:$VERSION-$BITBUCKET_BUILD_NUMBER .
    - docker tag $IMAGE:$VERSION-$BITBUCKET_BUILD_NUMBER $IMAGE:$VERSION
    - docker push $IMAGE:$VERSION-$BITBUCKET_BUILD_NUMBER
    - docker push $IMAGE:$VERSION

pipelines:
  branches:
    master:
      - parallel:
          - step:
              name: Build PostgreSQL 10
              script:
                - export VERSION=10 IMAGE="truemark/postgres-client"
                *build
          - step:
              name: Build PostgreSQL 11
              script:
                - export VERSION=11 IMAGE="truemark/postgres-client"
                *build
          - step:
              name: Build PostgreSQL 12
              script:
                - export VERSION=12 IMAGE="truemark/postgres-client"
                *build
